### ISSUE TITLE
[web] Website to promote the app

### ISSUE THREAD

**Issue by marciomribeiro** [easy-software-ufal/covidagglomerations#37]

**Comment by r4phael** [comment]
v0: [https://reverent-carson-0b2874.netlify.app/](url)

**TODO**

**Banner Principal**
- [ ] **Titulo:** _Covid Aglomerações_
- [ ] **Subtitulo:** _Covid Aglomerações é um app gratuito que ajuda a identificar aglomerações do vírus em todo o Brasil._

**Principais Funcionalidades**
- [ ] **Subtitulo:** _descrição_
- [ ] - Cadastro de Aglomerações: _descrição_
- [ ] - Envio de Fotos de Aglomerações: _descrição_
- [ ] - Visualização de Aglomerações: _descrição_
- [ ] - Confirmação de Aglomerações: _descrição_

**Banner Secundário 1**
- [ ] **Título**: _descrição_
- [ ] **Subtitulo:** _descrição_
- [ ] - _bullet1_
- [ ] - _bullet2_
- [ ] - _bullet3_
- [ ] - _bullet4_
- [ ] **Texto:** _descrição_

**Banner Secundário 2**
- [ ] **Título**: _descrição_
- [ ] **Subtitulo:** _descrição_
- [ ] **Texto:** _descrição_

**Galeria**
- [ ] **Titulo:** Galeria
- [ ] **Subtitulo:** _descrição_
**Fotos:**
- [ ] Foto 1
- [ ] Foto 2
- [ ] Foto 3
- [ ] Foto 4
- [ ] Foto 5
- [ ] Foto 6

**Na Mídia**
- [ ] **Titulo:** _Na Mídia_
- [ ] **Subtitulo:** _O que estão falando por aí a respeito do aplicativo._
**Links:**
- [ ] Midia 1
- [ ] Midia 2
- [ ] Midia 3
- [ ] Midia 4

**FAQ**
- [ ] **Titulo:** _Perguntas Frequentes_
- [ ] **Subtitulo:** _O que estão falando por aí a respeito do aplicativo._
**Perguntas & Respostas**
- [ ] Pergunta 1: _texto_
- [ ] Resposta 1: _texto_

- [ ] Pergunta 2: _texto_
- [ ] Resposta 2: _texto_

- [ ] Pergunta 3: _texto_
- [ ] Resposta 3: _texto_

- [ ] Pergunta 4: _texto_
- [ ] Resposta 4: _texto_

**Comment by marciomribeiro** [comment]
- [ ] Site do EASY apontando para aglomeracoes.org
- [ ] Melhorias no site do EASY (chatbot dos crawlers, chatbot de suprimentos, aglomerações, zika)
- [ ]  Melhorias no site do EASY (colocar a entrevista de quarta)
- [ ]  Melhorias no site do EASY (logotipo não está no meio, verticalmente, e parece grande demais proporcionalmente ao restante do site)

**Comment by marciomribeiro** [comment]
Usar essa foto em ambos os sites. No site do EASY, ela será a única.

![Screenshot_20200425-124035](https://user-images.githubusercontent.com/2229847/80288468-9823db00-870e-11ea-9e5b-1b8a6e2cc63f.png)

**Comment by marciomribeiro** [comment]
Usar essas duas fotos no site de aglomerações. Vamos esperar pelas novas telas do Arthur para colocarmos mais umas duas.

![Screenshot_20200425-124035](https://user-images.githubusercontent.com/2229847/80288492-bf7aa800-870e-11ea-8042-fea73b403751.png)


![Screenshot_20200425-124052](https://user-images.githubusercontent.com/2229847/80288488-b4c01300-870e-11ea-8406-12395364e1f5.png)

**Comment by marciomribeiro** [comment]
No site de aglomerações:

Seção 1:

- [ ] Colocar a foto do celular (imagem que mandei por e-mail)

- [ ] Colocar algum link para o mapa web (Moabson): "Acompanhe aqui as aglomerações!"

Seção 2:

- [ ] Principais funcionalidades: "Ao encontrar uma aglomeração na rua, os usuários podem cadastrar essa aglomeração usando o mapa. Assim que o cadastro ocorre, essa informação fica visível no mapa para os outros usuários do aplicativo, que identificam o tamanho da aglomeração através de cores."

- [ ] Cadastro de aglomerações: "Cadastre aglomerações usando as localidades do mapa, informando o número estimado de pessoas e outras informações como uso de máscaras e se há distanciamento entre as pessoas."

- [ ] Visualização de aglomerações: "Visualize através do mapa as aglomerações cadastradas bem como se há uso de máscaras, distanciamento entre as pessoas etc." 

- [ ] Tamanho das aglomerações: "Cores identificam quão grande são as aglomerações. De três a dez pessoas, usa-se a cor amarela; entre 11 e 50 pessoas, usa-se a cor laranja; e acima de 50 pessoas, usa-se a cor vermelha."

- [ ] Remova/Atualize Aglomerações: "Caso uma aglomeração não exista ou o número estimado de pessoas mudou, pode-se remover a aglomeração do mapa ou atualizá-la."

Seção 3:

- [ ] Mapa do Moabson

Seção 4:

- [ ] Galeria

Seção 5:

- [ ] Na mídia

Seção 6:

- [ ] Tirar o telefone
- [ ] Tirar redes sociais

**Comment by marciomribeiro** [comment]
- [ ] Tirar o "Fique por dentro"
- [ ] Colocar link para o mapa no botão "Mapa"
- [ ] Atualizar a foto da tela do celular
- [ ] Atualizar a galeria
